services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - mern_network
      
  frontend:
    build: ./frontend/Task-Manager
    ports:
      - "5173:5173"
    networks:
      - mern_network

networks:
  mern_network:
    driver: bridge
